import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Card from "./components/Card";
import MyForm from "./components/MyForm";
import { GoogleAnalytics } from '@next/third-parties/google'
import Script from "next/script";
import { GoogleTagManager } from '@next/third-parties/google'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

 {/* <GoogleTagManager gtmId="GTM-MLGS795P" /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <GoogleAnalytics />
        <MyForm /> */}
        {/* <Navbar />

        <Card/> */}
        <Script
        src={`https://www.googletagmanager.com/gtag/js?id=G-E9KSFS3GG8`}
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-E9KSFS3GG8');
        `}
      </Script>
        {children}
        {/* <GoogleAnalytics gaId="G-H86EYVTC69" /> */}
       
      </body>
    </html>
  );
}
